### ISSUE TITLE
With Progressive Inquiry activated, "Notify of follow-up comments by e-mail" not shown.

### ISSUE THREAD

**Issue by dgroos** [LeGroup/Fle4#46]
I just activated "Jet Pack" on the site. It includes lots of utilities including "e-mail Comment Notification" functionality--very important for any non-synchronous use-cases.
***********************************************************************************
![ss of a comment box without pi activated](https://f.cloud.github.com/assets/4097759/2297460/e69247d0-a0ac-11e3-997a-5ff56cff80bc.png)
***********************************************************************************
![ss of a comment box with pi activated](https://f.cloud.github.com/assets/4097759/2297463/ec3a0128-a0ac-11e3-9ef9-655fb8243d1e.png)

**Comment by dgroos** [comment]
I've re-tried the newest Jet Pack to see if it has started to work (magically!) with the newest versions of Wordpress (4.1.1): it doesn't.

Since this time I have also tried all comment-notification plugins that I could find that work in modern Wordpress, none of them work, that is, the comment-notification check box does not appear for the user. I wonder if it is difficult to get the check box to appear.

**Comment by tarmot** [comment]
Version 0.7.2 should fix this issue.
