### ISSUE TITLE
Idea: add 6th KT to progressive inquiry

### ISSUE THREAD

**Issue by dgroos** [LeGroup/Fle4#50]
We often consider that a "Problem" can be expressed as a problem statement or as a question and therefore FLE4 only has the knowledge type "Problem". However, a problem is actually an 'endlessly unfolding object of inquiry' (as per Bereiter) while a question is a tool used to interrogate. And therefore, "problem" and "question" are not only different kinds of knowledge objects they have very different epistemological roles in a discussion. So, that's a theoretical reason to split up the "problem" KT.

Pedagogically, having these 2 distinct KT's separately available would provide less sophisticated thinkers with an opportunity to get better at interrogation: I always have students who don't yet know how to ask a question to resolve their confusion, all they can do is say (often not very explicitly) the thing that they don't get, so by differentiating question from problem they are invited to share their problem but required to notice that it is a problem AND that they could have posted a question. Also, it will make them more aware when classmates post a question, modelling the process of breaking problems apart with questions. That's why I advocate considering adding an extra KT "Question" to FLE4.

**Comment by tarmot** [comment]
Can't disagree with this... And of course, you are free to edit the knowledge building set (the file format is a bit technical, but can be edited with a text editor) and make your own version.
